### ISSUE TITLE
Screen edges question?

### ISSUE THREAD

**Issue by zkrige** [nwutils/frameless-example#1]
Does dragging to the edge of the screen dock it there (in Windows) ?

**Comment by TheJaredWilcurt** [comment]
Yes, the window management system in Windows OS works the same with all windows, unless you specifically put resize restrictions (min/max height/width) on your window that would prevent it from taking up that portion of the screen when dragged to the edge (or the WinKey+arrow keys shortcuts are pressed).

Frameless vs framed windows act the same in this context (assuming you have designated a dragable region via CSS).

**Comment by zkrige** [comment]
thank you
